[package]
org = "wso2"
name = "devant"
version = "0.1.0"
title = "Slack-notification-GitHub-PR-merged"
distribution = "2201.13.1"

[[dependency]]
org = "ballerinax"
name = "slack"
version = "5.0.0"

[[dependency]]
org = "ballerinax"
name = "trigger.github"
version = "0.11.0"
